const fs = require("fs");
const path = require("path");

const TITLE = "Care-Connect Medical Practice - Redesigned User Flow";
const SUBTITLE = "Appointment Booking Process";
const INTRO =
  "This document outlines the redesigned user flow for booking a medical appointment through the Care-Connect Medical Practice online system. It includes decision points, branching logic, and patient pathways.";

const stepSummary = [
  "Starting Point: Patient lands on the homepage",
  "Decision: Patient chooses Book Appointment",
  "Step 1: Select appointment type",
  "Step 2: Select practitioner",
  "Step 3: Choose appointment format",
  "Step 4: Select date and time",
  "Step 5: Enter or confirm patient details",
  "Step 6: Add reason for visit",
  "Step 7: Complete insurance or payment step",
  "Step 8: Review and confirm",
  "End Point: Appointment confirmed",
];

const blocks = [
  [
    "STARTING POINT",
    "Patient lands on the Care-Connect Medical Practice homepage",
  ],
  [
    "DECISION: WHAT DOES THE PATIENT WANT TO DO?",
    "Options:\n- Book Appointment\n- Request Prescription Refill\n- View Test Results\n- Contact a Doctor\n- Register as New Patient\nFor this flow: Book Appointment",
  ],
  [
    "STEP 1 - SELECT APPOINTMENT TYPE",
    "General Consultation, Follow-up Visit, Chronic Care Review, Vaccination, Blood Test, Mental Health Consultation\nDecision: If unsure -> Show \"Help me choose\" assistant",
  ],
  [
    "STEP 2 - SELECT PRACTITIONER",
    "GP, Nurse, Specialist (if available)\nDecision: If no preferred practitioner -> Auto-assign based on availability",
  ],
  [
    "STEP 3 - CHOOSE APPOINTMENT FORMAT",
    "In-clinic visit, Video consultation, Telephone consultation\nDecision: If telehealth acceptable -> Show telehealth slots; otherwise -> Show in-clinic slots",
  ],
  [
    "STEP 4 - SELECT DATE & TIME",
    "Calendar view, Next available appointment, Filter by morning/afternoon/evening\nDecision: If selected time unsuitable -> Choose another slot",
  ],
  [
    "STEP 5 - PATIENT DETAILS",
    "Existing patient: Auto-fill details, confirm contact info, confirm GP registration\nNew patient: Full name, DOB, Address, NHS number (optional), Contact details, Medical history (short form)",
  ],
  [
    "STEP 6 - REASON FOR VISIT",
    "Symptoms, Duration, Additional notes, Optional photo upload",
  ],
  [
    "STEP 7 - INSURANCE / PAYMENT",
    "NHS patient -> Skip\nPrivate patient -> Enter insurance or self-pay",
  ],
  [
    "STEP 8 - REVIEW & CONFIRM",
    "Review appointment type, practitioner, date/time, location/telehealth link, personal details\nDecision: If correct -> Confirm Appointment; otherwise -> Edit details",
  ],
  [
    "END POINT - APPOINTMENT CONFIRMED",
    "Confirmation page, Email/SMS confirmation, Add to calendar, Pre-appointment instructions, Telehealth link (if applicable)",
  ],
];

function createReadme() {
  const readmePath = path.join(__dirname, "README.md");
  const lines = [
    `# ${TITLE}`,
    "",
    `## ${SUBTITLE}`,
    "",
    INTRO,
    "",
    "## What This Project Generates",
    "",
    "- `README.md`: Markdown version of the complete booking flow.",
    "",
    "## Prerequisites",
    "",
    "- Node.js 18+",
    "- npm",
    "",
    "## Quick Start",
    "",
    "1. Install dependencies:",
    "",
    "```bash",
    "npm install",
    "```",
    "",
    "2. Generate the README:",
    "",
    "```bash",
    "npm run generate-readme",
    "```",
    "",
    "## Generated Files",
    "",
    "- `README.md`",
    "",
    "## Flow Steps (Summary)",
    "",
  ];

  for (let index = 0; index < stepSummary.length; index += 1) {
    lines.push(`${index + 1}. ${stepSummary[index]}`);
  }

  lines.push(
    "",
    "## User Flow",
    "",
  );

  for (const [title, body] of blocks) {
    lines.push(`### ${title}`);
    lines.push("");

    for (const line of body.split("\n")) {
      if (line.startsWith("Options:")) {
        lines.push("Options:");
        const rawOptions = line.replace("Options:", "").trim();
        if (rawOptions.length > 0) {
          const options = rawOptions.split(",");
          for (const option of options) {
            lines.push(`- ${option.trim()}`);
          }
        }
      } else if (line.startsWith("Decision:")) {
        lines.push(`Decision: ${line.replace("Decision:", "").trim()}`);
      } else if (line.includes(":") && line.includes(",")) {
        lines.push(line);
      } else {
        lines.push(line);
      }
    }

    lines.push("");
  }

  lines.push("## Notes");
  lines.push("");
  lines.push("- `README.md` is auto-generated by `care_connect_flow.js`.");
  lines.push("- Manual edits to `README.md` may be overwritten the next time generation runs.");
  lines.push("- To change the flow content, edit `blocks` in `care_connect_flow.js` and re-run generation.");
  lines.push("");
  lines.push("## Troubleshooting");
  lines.push("");
  lines.push("- If generation fails, run `npm install` and retry `npm run generate-readme`.");
  lines.push("- Ensure the workspace path is writable.");
  lines.push("- If README content looks outdated, re-run generation after updating `blocks`.");

  fs.writeFileSync(readmePath, `${lines.join("\n")}\n`, "utf8");
  console.log(`README created at ${readmePath}`);
}

createReadme();
